backend: 
  name: github
  repo: bcorey85/vsainte-gatsby
  branch: blog
media_folder: static/assets
public_folder: /assets
collections: 
  - name: blog
    label: Blog
    folder: blog
    create: true
    slug: "{{year}}_{{slug}}"
    summary: "{{title}} - {{month}}/{{day}}/{{year}}"
    fields: 
      - { name: "type", label: "Type", widget: "hidden", default: "blog-post"}
      - { name: "date", label: "Date", widget: "datetime", dateFormat: "MM/DD/YYYY", timeFormat: false}
      - { name: "title", label: "Title", widget: "markdown", required: true }
      - { name: "image", label: "Image", widget: "image", required: false}
      - { name: "image-desc", label: "Image Description - REQUIRED for images", widget: "string", required: false}
      - { name: "video", label: "Video Link", widget: "string", required: false}
      - { name: "body", label: "Body", widget: "markdown", required: true  }
      - { name: "link", label: "Link", widget: "string", required: false}
      - { name: "link-text", label: "Link Text", widget: "string", required: false}
  - name: event
    label: Event
    folder: event
    create: true
    slug: "{{year}}_{{slug}}"
    summary: "{{title}} - {{month}}/{{day}}/{{year}}"
    fields: 
      - { name: "type", label: "Type", widget: "hidden", default: "event"}
      - { name: "date", label: "Date", widget: "datetime", dateFormat: "MM/DD/YYYY", timeFormat: false}
      - { name: "title", label: "Title", widget: "string", required: true }
      - { name: "location", label: "Location", widget: "string", required: true }
  - name: event-photo
    label: Event Photo
    folder: event-photo
    identifier_field: image-desc
    create: true
    slug: "{{year}}_{{slug}}"
    summary: "{{image-desc}} - {{month}}/{{day}}/{{year}}"
    fields: 
      - { name: "type", label: "Type", widget: "hidden", default: "event-photo"}
      - { name: "date", label: "Date", widget: "datetime", dateFormat: "MM/DD/YYYY", timeFormat: false}
      - { name: "image", label: "Image", widget: "image", required: true}
      - { name: "image-desc", label: "Image Description", widget: "string", required: true}
  - name: testimonial
    label: Testimonial
    folder: testimonial
    identifier_field: author
    create: true
    slug: "{{year}}_{{slug}}"
    summary: "{{author}} - {{month}}/{{day}}/{{year}}"
    fields: 
      - { name: "type", label: "Type", widget: "hidden", default: "testimonial"}
      - { name: "date", label: "Date", widget: "datetime", dateFormat: "MM/DD/YYYY", timeFormat: false}
      - { name: "author", label: "Author", widget: "string", required: true }
      - { name: "title1", label: "Title 1", widget: "string", required: false }
      - { name: "title2", label: "Title 2", widget: "string", required: false }
      - { name: "body", label: "Body", widget: "markdown", required: true  }